title: "JWT Scala"
description: "JSON Web Token (JWT) support for Scala. Optional helpers for Play Framework, Play JSON and Json4s"
version: 0.10.0
permalink: pretty
baseurl: "/jwt-scala"
url: "https://pauldijou.github.io"
highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks", "autolink", "strikethrough"]

versions: [0.9.2, 0.9.1, 0.9.0, 0.8.1, 0.8.0, 0.7.1, 0.7.0, 0.6.0, 0.5.1, 0.5.0, 0.4.1, 0.4.0, 0.4.0, 0.3.0, 0.2.1, 0.2.0, 0.1.0, 0.0.6, 0.0.5, 0.0.4, 0.0.3]
projects:
  - name: jwt-core
    description: pure Scala project.
  - name: jwt-play-json
    description: using the play-json lib but not Play Framework itself.
  - name: jwt-play
    description: developing a Play Framework app.
  - name: jwt-json4s
    description: using Json4s lib (either Native or Jackson implementation).
  - name: jwt-circe
    description: using Circe lib.

api:
  description: "There is no global API for the whole project but rather one API for each sub-project. Just pick the one you are using and enjoy awesome Scala documentation."
  legacy: "If you are using a **legacy** version of a project, the API is exactly the same as the non-legacy one."
  old:
    title: "Old APIs"
  others:
    title: "Other APIs"
    description: "If you need another version of the API, please go [here](/jwt-scala/api/)."
